import React from 'react';
import Link from 'next/link';

const Disclaimer = () => {
  return (
    <div className="container mx-auto px-4 py-8 text-gray-400">
      <h1 className="text-3xl font-bold mb-6 text-center">Disclaimer</h1>
      <p className="mb-4">
        The content and tools provided on <strong>QuantCoder FS</strong> are intended for educational and research purposes only.
        This platform does not offer financial, legal, or tax advice of any kind.
      </p>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">1. No Financial Advice</h2>
        <p>
          QuantCoder FS is not operated by a licensed financial advisor. The insights, research tools, and
          “Executive Summaries” shared on the platform or via Substack are informational in nature.
          Users should not interpret any content as a recommendation to invest, trade, or make financial decisions.
          Always consult with a qualified financial advisor before acting on any investment idea.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">2. Accuracy of Information</h2>
        <p>
          While we strive to provide accurate and timely information, we make no guarantees.
          Some data is sourced from third parties, which may occasionally be outdated or inaccurate.
          QuantCoder FS does not assume responsibility for external data errors or content that may become obsolete.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">3. Use of Algorithms and Tools</h2>
        <p>
          The tools and algorithmic outputs generated by QuantCoder FS are exploratory in nature.
          They are designed for prototyping and educational evaluation and should not be used for live trading
          without significant validation and professional oversight.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">4. Third-Party Links and Services</h2>
        <p>
          This platform may include links to third-party websites or use third-party APIs for data access.
          We do not endorse or control the accuracy, reliability, or privacy practices of any external service.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">5. Refer to Terms of Use</h2>
        <p>
          For legally binding terms—including warranty disclaimers and limitations of liability—please review our
          <Link href="/terms" className="text-blue-600 hover:underline"> Terms of Use</Link>.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">6. Contact</h2>
        <p>
          If you have any questions about this disclaimer, feel free to reach out:
        </p>
        <p className="font-medium">
          Email: <a href="mailto:smr.laignel@gmail.com" className="text-blue-600 hover:underline">smr.laignel@gmail.com</a>
        </p>
      </section>

      <p className="text-sm text-gray-400 mt-8 text-center">
        &copy; {new Date().getFullYear()} SL Mar. All rights reserved.
      </p>
      <div className="text-center mt-4">
        <Link href="/" className="text-gray-400 hover:underline">Return to Home</Link>
      </div>
    </div>
  );
};

export default Disclaimer;
